### ISSUE TITLE
ANSI cursor stdin edge cases

### ISSUE THREAD

**Issue by MaulingMonkey** [crossterm-rs/crossterm-cursor#3]
https://github.com/crossterm-rs/crossterm-cursor/blob/13f6c0878ac871750c5893689e4743ac8084c13b/src/sys/unix.rs#L45

This has a few problems:
1) This can discard real user input
2) This will likely hang if stdin was redirected, since it's not reading from the terminal associated with stdout

**Comment by zrzka** [comment]
Way more issues there, check this https://github.com/crossterm-rs/crossterm/issues/199 for more details.

**Comment by zrzka** [comment]
Moved this issues to [this comment](https://github.com/crossterm-rs/crossterm/issues/199#issuecomment-535392385). Reasons:

* Issues & Projects will be disabled on this repo
* See the [Future](https://github.com/crossterm-rs/crossterm-terminal#future)
  * Readme here will be updated in the #2
